name: Testes de API

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do projeto
        uses: actions/checkout@v2

      - name: Configurar Java
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Executar testes
        run: mvn clean test