name: Testes de API

on:
  push:
    branches: [master, development]

  pull_request:
    branches: [master]

jobs:
  api-tests:
    runs-on: windows-latest

    steps:
      - name: Checkout do projeto
        uses: actions/checkout@v2

      - name: Configurar Java
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Testar conexão com a API
        run: curl -I https://serverest.dev

      - name: Executar testes
        run: mvn clean test -Dtest=SuiteApiTest